-- 008_create_ops.sql
-- Operational housekeeping. Two tables:
--   pipeline_log — every workflow run, success or failure
--   access_log   — frontend query audit trail (Phase 4)
--
-- Run order: AFTER 001.

-- =============================================================================
-- PIPELINE LOG — every n8n workflow run lands here
-- =============================================================================
CREATE TABLE IF NOT EXISTS `oneeighty-warehouse.ops.pipeline_log` (
  run_id               STRING    NOT NULL,    -- uuid generated by n8n
  workflow             STRING    NOT NULL,    -- e.g. 'wf_shoptet'
  client_id            STRING,                 -- which client this iteration was for
  source               STRING,                 -- shoptet | ecomail | shopify | klaviyo | meta | gads | ga4 | instagram
  started_at           TIMESTAMP NOT NULL,
  finished_at          TIMESTAMP,
  duration_seconds     INT64,
  status               STRING    NOT NULL,    -- success | failure | partial | skipped
  rows_loaded          INT64,
  bytes_loaded         INT64,
  error_msg            STRING,
  retry_count          INT64     DEFAULT 0,
  trigger              STRING,                 -- cron | webhook | manual | reconcile
  ingested_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
PARTITION BY DATE(started_at)
CLUSTER BY workflow, client_id
OPTIONS (
  description = "Every n8n workflow run logs here. wf_health_check reads this daily and emails on failures.",
  require_partition_filter = TRUE
);

-- =============================================================================
-- ACCESS LOG — frontend audit (built in Phase 4, schema ready now)
-- =============================================================================
CREATE TABLE IF NOT EXISTS `oneeighty-warehouse.ops.access_log` (
  access_id            STRING    NOT NULL,
  user_email           STRING    NOT NULL,    -- who queried
  user_role            STRING,                 -- agency_admin | client_viewer
  client_id_scope      STRING,                 -- which client they were viewing
  query_type           STRING,                 -- 'kpi' | 'orders_drill' | 'cross_client'
  resource             STRING,                 -- which mart they hit
  ip_address           STRING,
  user_agent           STRING,
  accessed_at          TIMESTAMP NOT NULL,
  query_duration_ms    INT64,
  rows_returned        INT64
)
PARTITION BY DATE(accessed_at)
CLUSTER BY user_email, client_id_scope
OPTIONS (
  description = "Frontend audit log. Every authenticated query against the dashboard lands here.",
  require_partition_filter = TRUE
);
