/**
 * Highlights: one sentence and one small chart each, generated by explicit
 * rules from warehouse figures. Pure, safe anywhere, so the rules can be run
 * against fixture rows.
 *
 * ── The rules ──────────────────────────────────────────────────────────────
 * plan_pace       Clients with a Goals plan this month. The ring metric (CM3
 *                 when the plan targets it, else revenue) as a share of plan to
 *                 date, the mart.plan_pacing figure the Goals page shows,
 *                 against the same share 7 days earlier when that day is in the
 *                 same month. The earlier share and the line are cumulative
 *                 mart.plan_actuals_daily over mart.plan_targets_daily.
 * creative_share  Share of Meta spend on ads in their first 14 days, last 30
 *                 days (mart.mart_velocity_daily). The client with the lowest
 *                 share, drawn against every other client that has one.
 * revenue_vs_ly   Revenue month to date against the same days a year earlier.
 * revenue_7d      Average daily revenue, last 7 days against the 7 before.
 * amer_7d         aMER (new customer revenue over paid spend, a ratio of sums)
 *                 last 7 days against the 7 before.
 * cm3_vs_ly       CM3 month to date against the same days a year earlier.
 *
 * ── What makes a sentence ──────────────────────────────────────────────────
 * A rule fires for a client only when every day it sums is present with a
 * value; a gap never reads as zero, so a missing day means no sentence, not a
 * smaller number. Each sentence is assembled from the same values its chart
 * draws. No adjective is chosen by a threshold of this file's own: "up",
 * "down" and "more" are the sign of a difference, nothing else.
 *
 * ── Which ones show ────────────────────────────────────────────────────────
 * At most six. Every plan_pace card (the plan is what the agency is measured
 * on), then creative_share, then one card per remaining rule in the order
 * above: of the clients the earlier cards named least, the one with the
 * largest relative change, so the cards spread over the book.
 */

import { formatMoney, formatPercent, formatRatio } from "@/lib/format";
import { fmtPace } from "@/lib/plan/format";
import type { ClientHealth } from "@/lib/home/types";
import { addDays, completeSum, inWindow, monthStart, monthWord, paceSeries, shortDay, windowAmer, yearEarlier } from "./series";
import type { ClientSeries, CreativeShare, Highlight, HighlightRule, SummaryInput } from "./types";

export const MAX_HIGHLIGHTS = 6;

interface Candidate {
  highlight: Highlight;
  /** Relative size of the change, for picking between clients of one rule. */
  score: number;
}

const possessive = (name: string) => `${name}'s`;

function link(path: string, clientId: string): string {
  return `${path}?client=${encodeURIComponent(clientId)}`;
}

/** "1 to 7 October", or "1 October" for a single day. */
function dayRange(from: string, to: string): string {
  const month = monthWord(to);
  const a = Number(from.slice(8, 10));
  const b = Number(to.slice(8, 10));
  return a === b ? `${b} ${month}` : `${a} to ${b} ${month}`;
}

/** Percentage of a change without its sign: 0.183 -> "18.3%". */
function size(fraction: number): string {
  return formatPercent(Math.abs(fraction));
}

function isFlat(fraction: number): boolean {
  return size(fraction) === formatPercent(0);
}

/* ------------------------------------------------------------------------ */
/* plan_pace                                                                */
/* ------------------------------------------------------------------------ */

function planPace(c: ClientHealth, s: ClientSeries | undefined): Candidate | null {
  const row = c.focus;
  if (!row || !c.clientId || !c.currency || row.pacePct === null) return null;
  const metric = row.metric === "cm3" ? "cm3" : row.metric === "revenue" ? "revenue" : null;
  if (!metric) return null;
  const label = metric === "cm3" ? "CM3" : "revenue";
  const to = row.asOf;
  const from = monthStart(to);
  const pace = s ? paceSeries(s.days, metric, from, to) : [];
  const weekAgo = addDays(to, -7);
  const prior = weekAgo >= from ? pace.find((p) => p.date === weekAgo)?.pace ?? null : null;
  const now = row.pacePct;

  let tail: string;
  if (prior !== null) {
    const nowText = fmtPace(now);
    const priorText = fmtPace(prior);
    tail = nowText === priorText ? "the same as a week ago" : `${now > prior ? "up" : "down"} from ${priorText} a week ago`;
  } else {
    const n = row.daysElapsed;
    tail = `${n} ${n === 1 ? "day" : "days"} into ${monthWord(to)}`;
  }

  // The line is drawn only when its last point is the pacing figure the
  // sentence quotes (to the shown decimal); otherwise the bars carry the two
  // pacing figures themselves, so the chart can never disagree with the words.
  const last = pace[pace.length - 1];
  const lineAgrees = pace.length >= 3 && last.date === to && fmtPace(last.pace) === fmtPace(now);
  const chart: Highlight["chart"] = lineAgrees
    ? {
        kind: "line",
        points: pace.map((p) => p.pace),
        reference: { value: 100, label: "Plan" },
        startLabel: shortDay(pace[0].date),
        endLabel: shortDay(last.date),
        endText: fmtPace(now),
      }
    : {
        kind: "compare",
        rows: [
          { label: "Actual to date", value: row.actual ?? 0, text: formatMoney(row.actual, c.currency), emphasis: true },
          { label: "Plan to date", value: row.targetToDate ?? 0, text: formatMoney(row.targetToDate, c.currency), emphasis: false },
        ],
      };

  return {
    score: Math.abs(now - 100) / 100,
    highlight: {
      id: `plan_pace:${c.clientId}`,
      rule: "plan_pace",
      metric,
      category: metric === "cm3" ? "CM3" : "Revenue",
      clientId: c.clientId,
      clientName: c.name,
      sentence: `${possessive(c.name)} ${label} is ${fmtPace(now)} of plan to date, ${tail}.`,
      caption: null,
      source:
        "Share of plan to date: mart.plan_pacing, as on Goals. A week earlier and the line: cumulative mart.plan_actuals_daily over the plan curve in mart.plan_targets_daily.",
      asOf: to,
      chart,
      href: link("/goals", c.clientId),
    },
  };
}

/* ------------------------------------------------------------------------ */
/* creative_share                                                           */
/* ------------------------------------------------------------------------ */

function creativeShare(clients: ClientHealth[], creative: CreativeShare[]): Candidate | null {
  const named = creative.flatMap((v) => {
    const c = clients.find((x) => x.clientId === v.clientId);
    return c && v.share30d !== null && v.spend30d > 0 ? [{ ...v, share: v.share30d, name: c.name }] : [];
  });
  if (!named.length) return null;
  const subject = named.reduce((lo, v) => (v.share < lo.share ? v : lo));
  const pct = (v: number) => formatPercent(v, { decimals: 0 });
  return {
    score: 1,
    highlight: {
      id: `creative_share:${subject.clientId}`,
      rule: "creative_share",
      metric: "creative",
      category: "Creative",
      clientId: subject.clientId,
      clientName: subject.name,
      sentence: `${subject.name} spent ${pct(subject.share)} of its Meta budget on new creative in the last 30 days.`,
      caption: named.length > 1 ? `Lowest of ${named.length} clients` : null,
      source: `mart.mart_velocity_daily: spend on ads in their first 14 days of delivery over all Meta spend, 30 days to ${shortDay(subject.through)}.`,
      asOf: subject.through,
      chart: {
        kind: "compare",
        rows: [...named]
          .sort((a, b) => b.share - a.share)
          .map((v) => ({ label: v.name, value: v.share, text: pct(v.share), emphasis: v.clientId === subject.clientId })),
      },
      href: link("/creative/velocity", subject.clientId),
    },
  };
}

/* ------------------------------------------------------------------------ */
/* Month to date against last year                                          */
/* ------------------------------------------------------------------------ */

function versusLastYear(c: ClientHealth, s: ClientSeries | undefined, field: "revenue" | "cm3"): Candidate | null {
  if (!s || !c.clientId || !c.currency) return null;
  const to = s.asOf;
  const from = monthStart(to);
  const lyFrom = yearEarlier(from);
  const lyTo = yearEarlier(to);
  const cur = completeSum(s.days, field, from, to);
  const ly = completeSum(s.days, field, lyFrom, lyTo);
  // A year with no sales is not a base, for CM3 as for revenue (as Home).
  const lyRevenue = field === "revenue" ? ly : completeSum(s.days, "revenue", lyFrom, lyTo);
  if (cur === null || ly === null || lyRevenue === null || lyRevenue <= 0) return null;
  const year = to.slice(0, 4);
  const lastYear = lyTo.slice(0, 4);
  const range = dayRange(from, to);
  const money = (v: number) => formatMoney(v, c.currency as string);
  const chart: Highlight["chart"] = {
    kind: "compare",
    rows: [
      { label: year, value: cur, text: money(cur), emphasis: true },
      { label: lastYear, value: ly, text: money(ly), emphasis: false },
    ],
  };

  if (field === "revenue") {
    const change = cur / ly - 1;
    const sentence = isFlat(change)
      ? `${possessive(c.name)} revenue for ${range} is level with the same days last year.`
      : `${possessive(c.name)} revenue for ${range} is ${change > 0 ? "up" : "down"} ${size(change)} on the same days last year.`;
    return {
      score: Math.abs(change),
      highlight: {
        id: `revenue_vs_ly:${c.clientId}`,
        rule: "revenue_vs_ly",
        metric: "revenue",
        category: "Revenue",
        clientId: c.clientId,
        clientName: c.name,
        sentence,
        caption: null,
        source: `mart.plan_actuals_daily, revenue (goods ex VAT, after discounts and refunds) ${range} against ${shortDay(lyFrom)} to ${shortDay(lyTo)} ${lastYear}.`,
        asOf: to,
        chart,
        href: link("/snapshot", c.clientId),
      },
    };
  }

  const diff = cur - ly;
  const diffText = formatMoney(Math.abs(diff), c.currency);
  const sentence =
    diffText === formatMoney(0, c.currency)
      ? `${c.name} made the same CM3 over ${range} as on the same days last year.`
      : `${c.name} made ${diffText} ${diff > 0 ? "more" : "less"} CM3 over ${range} than on the same days last year.`;
  return {
    score: Math.abs(diff) / Math.max(Math.abs(ly), 1),
    highlight: {
      id: `cm3_vs_ly:${c.clientId}`,
      rule: "cm3_vs_ly",
      metric: "cm3",
      category: "CM3",
      clientId: c.clientId,
      clientName: c.name,
      sentence,
      caption: null,
      source: `mart.plan_actuals_daily, CM3 (revenue minus COGS, fulfilment and paid spend) ${range} against the same days of ${lastYear}. Live data, not the contract baseline.`,
      asOf: to,
      chart,
      href: link("/snapshot", c.clientId),
    },
  };
}

/* ------------------------------------------------------------------------ */
/* Last 7 days against the 7 before                                         */
/* ------------------------------------------------------------------------ */

function revenueWeek(c: ClientHealth, s: ClientSeries | undefined): Candidate | null {
  if (!s || !c.clientId || !c.currency) return null;
  const to = s.asOf;
  const now = completeSum(s.days, "revenue", addDays(to, -6), to);
  const prev = completeSum(s.days, "revenue", addDays(to, -13), addDays(to, -7));
  if (now === null || prev === null || prev <= 0) return null;
  const change = now / prev - 1;
  const money = (v: number) => formatMoney(v, c.currency as string);
  const days = inWindow(s.days, addDays(to, -13), to);
  const sentence = isFlat(change)
    ? `${c.name} averaged ${money(now / 7)} a day in revenue over the last 7 days, the same as the 7 days before.`
    : `${c.name} averaged ${money(now / 7)} a day in revenue over the last 7 days, ${size(change)} ${change > 0 ? "more" : "less"} than the 7 days before.`;
  return {
    score: Math.abs(change),
    highlight: {
      id: `revenue_7d:${c.clientId}`,
      rule: "revenue_7d",
      metric: "revenue",
      category: "Revenue",
      clientId: c.clientId,
      clientName: c.name,
      sentence,
      caption: null,
      source: `mart.plan_actuals_daily, daily revenue ${shortDay(addDays(to, -6))} to ${shortDay(to)} against ${shortDay(addDays(to, -13))} to ${shortDay(addDays(to, -7))}.`,
      asOf: to,
      chart: {
        kind: "columns",
        bars: days.map((d, i) => ({ label: shortDay(d.date), value: d.revenue, emphasis: i >= 7 })),
        averages: [
          { from: 0, to: 6, value: prev / 7, text: money(prev / 7), emphasis: false },
          { from: 7, to: 13, value: now / 7, text: money(now / 7), emphasis: true },
        ],
      },
      href: link("/snapshot", c.clientId),
    },
  };
}

function amerWeek(c: ClientHealth, s: ClientSeries | undefined): Candidate | null {
  if (!s || !c.clientId) return null;
  const to = s.asOf;
  const now = windowAmer(s.days, addDays(to, -6), to);
  const prev = windowAmer(s.days, addDays(to, -13), addDays(to, -7));
  if (now === null || prev === null || prev <= 0) return null;
  const nowText = formatRatio(now);
  const prevText = formatRatio(prev);
  const tail = nowText === prevText ? "the same as the 7 days before" : `${now > prev ? "up" : "down"} from ${prevText} the 7 days before`;
  // Trailing 7-day aMER for each of the last 28 days, a ratio of sums each time.
  const points: Array<number | null> = [];
  for (let back = 27; back >= 0; back--) {
    const end = addDays(to, -back);
    points.push(windowAmer(s.days, addDays(end, -6), end));
  }
  const planTarget = c.amer.row?.target ?? null;
  return {
    score: Math.abs(now / prev - 1),
    highlight: {
      id: `amer_7d:${c.clientId}`,
      rule: "amer_7d",
      metric: "amer",
      category: "aMER",
      clientId: c.clientId,
      clientName: c.name,
      sentence: `${possessive(c.name)} aMER was ${nowText} over the last 7 days, ${tail}.`,
      caption: null,
      source:
        "mart.plan_actuals_daily: new customer revenue over paid spend, summed over each 7-day window. The line is that window ending on each day." +
        (planTarget !== null ? " Plan: the month's aMER target in mart.plan_pacing." : ""),
      asOf: to,
      chart: {
        kind: "line",
        points,
        reference: planTarget !== null ? { value: planTarget, label: "Plan" } : null,
        startLabel: shortDay(addDays(to, -27)),
        endLabel: shortDay(to),
        endText: nowText,
      },
      href: link("/paid", c.clientId),
    },
  };
}

/* ------------------------------------------------------------------------ */
/* Selection                                                                */
/* ------------------------------------------------------------------------ */

const ONE_PER_RULE: HighlightRule[] = ["revenue_vs_ly", "revenue_7d", "amer_7d", "cm3_vs_ly"];

export function buildHighlights({ clients, series, creative }: Pick<SummaryInput, "clients" | "series" | "creative">): Highlight[] {
  const seriesOf = (id: string | null) => (id ? series.find((s) => s.clientId === id) : undefined);
  const picked: Highlight[] = [];
  const uses = new Map<string, number>();
  const take = (h: Highlight) => {
    if (picked.length >= MAX_HIGHLIGHTS) return;
    picked.push(h);
    uses.set(h.clientId, (uses.get(h.clientId) ?? 0) + 1);
  };

  clients
    .map((c) => planPace(c, seriesOf(c.clientId)))
    .filter((x): x is Candidate => x !== null)
    .sort((a, b) => b.score - a.score)
    .forEach((x) => take(x.highlight));

  const creativeCard = creativeShare(clients, creative);
  if (creativeCard) take(creativeCard.highlight);

  const byRule: Record<string, Candidate[]> = {};
  for (const c of clients) {
    const s = seriesOf(c.clientId);
    const found = [versusLastYear(c, s, "revenue"), revenueWeek(c, s), amerWeek(c, s), versusLastYear(c, s, "cm3")];
    for (const x of found) if (x) (byRule[x.highlight.rule] ??= []).push(x);
  }
  for (const rule of ONE_PER_RULE) {
    // The client named least so far, then the largest change.
    const used = (x: Candidate) => uses.get(x.highlight.clientId) ?? 0;
    const choice = (byRule[rule] ?? []).sort((a, b) => used(a) - used(b) || b.score - a.score)[0];
    if (choice) take(choice.highlight);
  }
  return picked;
}

