/**
 * Home, "Summary" variant: the data model. Pure types, safe in client components.
 *
 * The page is the iPhone Health app's Summary tab translated to the agency:
 * Pinned (one activity card per client), Highlights (sentences generated by
 * explicit rules from warehouse figures) and the Clients list. Every figure
 * here arrives finished from a named source; anything a source cannot give is
 * null and carries the reason, so the page can render n/a with an (i).
 */

import type { ClientHealth } from "@/lib/home/types";

/** The metric families, each with its own Health colour (see components/home/health/palette.ts). */
export type MetricKey = "revenue" | "cm3" | "amer" | "creative";

/** One day of a client's plan actuals, with the month's cumulative targets where the plan has them. */
export interface DayPoint {
  date: string;
  revenue: number | null;
  cm3: number | null;
  /** New customer revenue, the aMER numerator. */
  ncr: number | null;
  /** Paid spend, the aMER denominator. Null on a day with missing spend. */
  paid: number | null;
  /** Cumulative month target to this day (mart.plan_targets_daily.target_cum_month). */
  revenueTargetCum: number | null;
  cm3TargetCum: number | null;
}

export interface ClientSeries {
  clientId: string;
  /** Last day of data in mart.plan_actuals_daily. */
  asOf: string;
  /** Ascending, the last 42 days to `asOf` plus the same month-to-date days a year earlier. */
  days: DayPoint[];
}

/** Trailing Meta figures from mart.mart_velocity_daily (lib/queries/velocity.ts). */
export interface CreativeShare {
  clientId: string;
  through: string;
  /** New creative spend over spend, last 30 days. Null when the history is too short to tell. */
  share30d: number | null;
  spend30d: number;
  currency: string | null;
}

/* ------------------------------------------------------------------------ */
/* Pinned                                                                   */
/* ------------------------------------------------------------------------ */

/** One ring and the figure beside it. */
export interface RingFigure {
  metric: Exclude<MetricKey, "creative">;
  label: string;
  /** Actual to date, formatted. `n/a` when missing. */
  actualText: string;
  /** What the ring is measured against, formatted ("CZK 430K"), or null when there is nothing. */
  targetText: string | null;
  /** Actual over the comparison: 1 = a full ring. Null draws an empty track. */
  fraction: number | null;
  /** Small line under the figure ("96.1% of plan to date", "No target"). */
  caption: string;
  /** Why the figure is n/a, or why the ring is empty. Shown in an (i). */
  note: string | null;
}

export interface PinnedCard {
  clientId: string;
  name: string;
  /** "plan": three rings against the Goals plan to date. "lastYear": one neutral ring, revenue against the same days last year. */
  mode: "plan" | "lastYear";
  rings: RingFigure[];
  /** Month-to-date figures shown without a ring (the no-plan card's CM3 and aMER). */
  extras: RingFigure[];
  asOf: string | null;
  monthLabel: string | null;
  href: string;
}

/* ------------------------------------------------------------------------ */
/* Highlights                                                               */
/* ------------------------------------------------------------------------ */

/** Which rule produced a highlight. Each rule is documented in lib/home/health/highlights.ts. */
export type HighlightRule = "plan_pace" | "creative_share" | "revenue_vs_ly" | "revenue_7d" | "amer_7d" | "cm3_vs_ly";

export interface ChartBar {
  label: string;
  value: number | null;
  /** Drawn in the metric colour; the rest are grey. */
  emphasis: boolean;
}

export interface CompareRow {
  label: string;
  value: number;
  text: string;
  emphasis: boolean;
}

export type HighlightChart =
  /** Daily columns, the last `emphasised` of them in colour, with an average line over each half. */
  | { kind: "columns"; bars: ChartBar[]; averages: Array<{ from: number; to: number; value: number; text: string; emphasis: boolean }> }
  /** Two or more horizontal bars on one scale, the Health comparison chart. */
  | { kind: "compare"; rows: CompareRow[] }
  /** A line with an optional reference level ("Plan" at 100%). */
  | {
      kind: "line";
      points: Array<number | null>;
      reference: { value: number; label: string } | null;
      startLabel: string;
      endLabel: string;
      endText: string;
    };

export interface Highlight {
  id: string;
  rule: HighlightRule;
  metric: MetricKey;
  /** Category title in the card header ("Revenue", "CM3"). */
  category: string;
  clientId: string;
  clientName: string;
  /** The generated sentence. Every number in it is in the chart or the source note. */
  sentence: string;
  /** Short line under the chart ("Lowest of 4 clients"). Null when nothing to add. */
  caption: string | null;
  /** The (i): which objects the sentence is computed from, and how. */
  source: string;
  /** Last day of data behind the sentence. */
  asOf: string | null;
  chart: HighlightChart;
  href: string;
}

/* ------------------------------------------------------------------------ */
/* Clients list                                                             */
/* ------------------------------------------------------------------------ */

export type ChipTone = "positive" | "info" | "warning" | "negative" | "neutral";

export interface Chip {
  label: string;
  tone: ChipTone;
  tip: string;
}

export interface MoneyFact {
  label: string;
  /** Formatted, or null for n/a. */
  text: string | null;
  /** Small muted suffix ("/ mo", "04/26"). */
  suffix: string | null;
  /** About the figure when present, why it is n/a when not. */
  tip: string;
}

export interface ClientRow {
  key: string;
  name: string;
  chips: Chip[];
  money: MoneyFact[];
  /** Goals page of the client; null for a client the warehouse does not hold. */
  href: string | null;
  crmUrl: string | null;
}

export interface SummaryData {
  pinned: PinnedCard[];
  highlights: Highlight[];
  clients: ClientRow[];
  /** Highlight sources that could not be read, for the (i) on the Highlights title. */
  gaps: string[];
}

/** What the pure builders take: the Home read plus the two series this page adds. */
export interface SummaryInput {
  clients: ClientHealth[];
  series: ClientSeries[];
  creative: CreativeShare[];
  gaps: string[];
}
