CREATE TABLE `oneeighty-warehouse.mart.rpt_customer_entry`
(
  client_id STRING,
  customer_id STRING,
  cohort_month DATE,
  first_order_date DATE,
  classes_configured BOOL,
  entry_class STRING,
  entry_class_first_order STRING,
  has_unmatched_line BOOL,
  first_order_revenue NUMERIC,
  first_day_orders INT64,
  orders_total INT64,
  order_days_total INT64,
  second_order_date DATE,
  third_order_date DATE,
  first_full_date DATE,
  second_order_any_date DATE,
  third_order_any_date DATE,
  first_full_any_date DATE,
  data_start_date DATE,
  history_guard_days INT64,
  as_of_date DATE,
  cutoff_date DATE,
  is_early BOOL,
  observed_days INT64,
  days_to_2nd INT64,
  days_2nd_to_3rd INT64,
  days_to_full INT64,
  n_customer INT64,
  m30 INT64,
  m60 INT64,
  m90 INT64,
  m180 INT64,
  m365 INT64,
  r30 INT64,
  r60 INT64,
  r90 INT64,
  r180 INT64,
  r365 INT64,
  u30 INT64,
  u60 INT64,
  u90 INT64,
  u180 INT64,
  u365 INT64,
  is_discovery INT64,
  has_second INT64,
  m23_180 INT64,
  r23_180 INT64,
  dm90 INT64,
  du90 INT64,
  dm180 INT64,
  du180 INT64,
  dm365 INT64,
  du365 INT64,
  refreshed_at TIMESTAMP
)
CLUSTER BY client_id, cohort_month
OPTIONS(
  description="One row per client and customer (customer_id = SHA256 of client and email, no email stored): first order date, entry class from ref.product_classes (NULL when the client has no classes), 2nd and 3rd order days, first later full-size order, cut-off and maturity, horizon flags m/r/u for 30, 60, 90, 180, 365 days (INT64 0/1, sum them), 2nd to 3rd ladder, early flag (left censoring). Built by mart.sp_refresh_rpt_customer_entry (hourly). Migration 258."
);
