CREATE TABLE `oneeighty-warehouse.mart.rpt_ad_launch`
(
  client_id STRING,
  ad_id STRING,
  ad_name STRING,
  campaign_id STRING,
  adset_id STRING,
  currency STRING,
  first_date DATE,
  last_date DATE,
  active_days INT64,
  spend NUMERIC,
  revenue NUMERIC,
  purchases INT64,
  impressions INT64,
  video_plays INT64,
  history_start DATE,
  through DATE,
  age_days INT64,
  is_preexisting BOOL,
  is_video BOOL,
  asset_key STRING,
  is_relaunch BOOL,
  concept_id STRING,
  concept_name STRING,
  persona_id STRING,
  format_tag STRING,
  production_type STRING,
  prior_roas NUMERIC,
  refreshed_at TIMESTAMP,
  video_start_share FLOAT64,
  adset_first_date DATE,
  is_new_adset BOOL,
  attribution_split_days INT64,
  attribution_split_complete BOOL,
  purchases_7d_click INT64,
  revenue_7d_click NUMERIC,
  purchases_1d_view INT64,
  revenue_1d_view NUMERIC,
  purchases_1d_ev INT64,
  revenue_1d_ev NUMERIC,
  prior_roas_7d_click NUMERIC,
  prior_split_coverage NUMERIC,
  purchases_7dc_1dv INT64,
  revenue_7dc_1dv NUMERIC,
  prior_roas_7dc_1dv NUMERIC
)
CLUSTER BY client_id
OPTIONS(
  description="One row per Meta ad: first delivery date, lifetime totals to the latest loaded day, pre-existing and relaunch flags, video flag and share, ad set launch context, 12 month client ROAS prior, lifetime purchases per attribution window (7d_click, 1d_view, 1d_ev) and on the standard basis 7d_click + 1d_view (NULL until the split covers every delivery day). Built from mart.mart_meta_ad_perf by mart.sp_refresh_rpt_ad_launch (daily). Base for the creative hit rate. Migrations 254, 255 and 256."
);
